sudo: required
services: 
  - docker
language: node_js

node_js:

- "8"

before_install:
  - docker build -t kalikarthik/docker-react -f Dockerfile.dev .

script:
  - docker run kalikarthik/docker-react npm run test -- --coverage