sudo: required
services: 
  - docker
language: node_js

node_js:

- "8"

before_install:
  - docker build -t kalikarthik/docker-react -f Dockerfile.dev .

script:
  - - docker run -e CI=true kalikarthik/docker-react npm run test -- --watchAll=false

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-west-2-185798489775"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"